### ISSUE TITLE
GitHub Actions & environment variables

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/xgqfrms#23]
# GitHub Actions & environment variables

https://github.com/xgqfrms/xgqfrms/commit/d11d6f42f09fd01cc0f9c36d7fb6f5c65e6709fd

```yml
# This is a basic workflow to help you get started with Actions

name: 🚀 dev token for main branch 👻

# 控制 action 何时运行
# 在 push 或 pull 请求时触发工作流程事件，但仅针对  master 分支
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ mian ]

# 一个 workflow 运行由可以串行或并行运行的一个或多个 jobs 组成
jobs:
  # 此工作流程仅包含一个名为 "dev-deploymen" 的 job /job 名称: dev-deploymen
  dev-deployment:
    # job 将运行的 runner 类型(执行的系统环境 Linux/ macOS / Windows)
    runs-on: ubuntu-latest
    # 使用 environment `dev-env`
    environment: dev-env
    
    # 步骤表示将作为 job 一部分执行的一系列 tasks
    steps:
      # 在 $GITHUB_WORKSPACE下检出你的repository，以便你的 job 可以访问它
      # 使用 - uses 
      - uses: actions/checkout@v2
      # 使用 - name + uses
      - name: 使用 自定义 github action: github fe oss project template
        uses: xgqfrms/github-fe-oss-project-template@v0.0.1
          with:
            # 使用 dev-env 下的 token， secrets.DEV_TOKEN_FOR_MAIN
            ghToken: ${{ secrets.DEV_TOKEN_FOR_MAIN }}

      # 使用 runners shell 运行单个命令
      - name: Run a one-line script ✅ 👨🏻‍💻
        run: echo 正在执行单个命令!

      # 使用 runners shell 运行一组命令
      - name: Run a multi-line script ✅ 👨🏻‍💻
        run: |
          echo 正在执行多个命令的
          echo finished 🎉

```

<img width="818" alt="image" src="https://user-images.githubusercontent.com/7291672/198990847-ae6d3044-a53a-4482-a668-6a63921e890c.png">

https://docs.github.com/en/actions/learn-github-actions/environment-variables#about-environment-variables

https://docs.github.com/en/actions/learn-github-actions/contexts#env-context

**Comment by xgqfrms** [comment]
#  env

https://github.com/xgqfrms/xgqfrms/settings/environments


https://github.com/xgqfrms/xgqfrms/settings/environments/596054267/edit


<img width="798" alt="image" src="https://user-images.githubusercontent.com/7291672/198991517-5497c9e6-2db5-4226-b54f-8f955794e98f.png">

https://docs.github.com/actions/reference/environments

**Comment by xgqfrms** [comment]
```yml
name: GitHub-Profile-3D-Contrib
on:
  # Schedule updates (each day 24 点 00 分自动执行一次)
  # corn 参考
  # https://img2020.cnblogs.com/blog/740516/202012/740516-20201203230232201-913405527.png
  # https://www.cnblogs.com/xgqfrms/p/14079442.html
  schedule: [{cron: "59 23 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}

# https://docs.github.com/en/actions/learn-github-actions/contexts
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

# https://github.com/xgqfrms/xgqfrms/settings/secrets/actions
# - uses: actions/checkout@v3

# https://docs.github.com/en/actions/learn-github-actions/environment-variables

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
      # 执行单行命令 ??? env
      # - name: "Hello env $EMAIL"
      #   run: echo "$EMAIL"
      # - name: "Hello env $FLAG"
      #   if: ${{ env.FLAG == 'true' }}
      #   run: echo "$FLAG"
      # 执行多行命令
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email ${{ secrets.EMAIL }}
          git add -A .
          git commit -m "feat: update GitHub 3D Profile"
          git push
        # run: |
        #   git config user.name ${{ github.repository_owner }}
        #   git config user.email xgqfrms@xgqfrms.xyz
        #   git add -A .
        #   git commit -m "feat: update GitHub 3D Profile"
        #   git push

```

https://github.com/xgqfrms/xgqfrms/blob/master/.github/workflows/profile-night-rainbow.yml

**Comment by xgqfrms** [comment]
```yml

      - name: Print env ❓
        run: env | sort

```

https://stackoverflow.com/questions/70700244/in-a-github-actions-workflow-how-can-you-determine-the-organziation-where-the-c


https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/using-github-cli-in-workflows

**Comment by xgqfrms** [comment]
# Node.js 12.x bug

yoshi389111/github-profile-3d-contrib


<img width="1310" alt="image" src="https://user-images.githubusercontent.com/7291672/198992736-2d97fd2a-6cec-4b6a-b3bd-2fe695a411e1.png">


https://github.com/xgqfrms/xgqfrms/actions/runs/3360642041


<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7291672/198994475-56b8cfec-1b25-489e-8cc3-48e29c1a660d.png">


https://github.com/xgqfrms/xgqfrms/actions/runs/3360733405


???

https://github.com/marketplace/actions/github-profile-3d-contrib

https://github.com/yoshi389111/github-profile-3d-contrib/releases

**Comment by xgqfrms** [comment]
https://github.com/yoshi389111/github-profile-3d-contrib/issues/43

https://github.com/xgqfrms/xgqfrms/actions/runs/3368315358

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/7291672/199205301-04ecc9b9-f6c5-4813-bd9d-16403673e940.png">

https://github.com/yoshi389111/github-profile-3d-contrib/blob/main/action.yml

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/7291672/199205681-2003840f-4207-49da-aa7d-ad164c95a739.png">

> new version

https://github.com/xgqfrms/github-profile-3d-contrib-2022


# Node.js 16 ❓solution ✅

https://github.com/xgqfrms/github-profile-3d-contrib-2022/releases/tag/v0.0.1

https://github.com/xgqfrms/github-profile-3d-contrib-2022

https://github.com/marketplace/actions/github-profile-3d-contrib-2022

```yml

- name: GitHub-Profile-3D-Contrib-2022
  uses: xgqfrms/github-profile-3d-contrib-2022@v0.0.1


```




https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

<img width="719" alt="image" src="https://user-images.githubusercontent.com/7291672/199205238-2ee6d26a-69f8-4970-9b88-d67be0d01ca1.png">


https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

**Comment by xgqfrms** [comment]
```yml
name: GitHub-Profile-3D-Contrib
on:
  # Schedule updates (each day 24 点 00 分自动执行一次)
  # corn 参考
  # https://img2020.cnblogs.com/blog/740516/202012/740516-20201203230232201-913405527.png
  # https://www.cnblogs.com/xgqfrms/p/14079442.html
  schedule: [{cron: "59 23 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}

# https://docs.github.com/en/actions/learn-github-actions/contexts
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

# https://github.com/xgqfrms/xgqfrms/settings/secrets/actions
# - uses: actions/checkout@v3

# https://docs.github.com/en/actions/learn-github-actions/environment-variables

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # - uses: actions/checkout@v3
      - uses: actions/checkout@v2
      # - uses: yoshi389111/github-profile-3d-contrib@latest
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
      # 执行单行命令 ??? env
      # - name: "Hello env $EMAIL"
      #   run: echo "$EMAIL"
      # - name: "Hello env $FLAG"
      #   if: ${{ env.FLAG == 'true' }}
      #   run: echo "$FLAG"
      # 执行多行命令
      - name: Print env ❓
        run: env | sort
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email xgqfrms@xgqfrms.xyz
          git add -A .
          git commit -m "feat: update GitHub 3D Profile"
          git push
        # run: |
        #   git config user.name ${{ github.repository_owner }}
        #   git config user.email xgqfrms@xgqfrms.xyz  git config user.email ${{ secrets.EMAIL }}
        #   git add -A .
        #   git commit -m "feat: update GitHub 3D Profile"
        #   git push


```

**Comment by xgqfrms** [comment]
#  backup

```yml

name: GitHub-Profile-3D-Contrib
on:
  # Schedule updates (each day 24 点 00 分自动执行一次)
  # corn 参考
  # https://img2020.cnblogs.com/blog/740516/202012/740516-20201203230232201-913405527.png
  # https://www.cnblogs.com/xgqfrms/p/14079442.html
  schedule: [{cron: "59 23 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}

# https://docs.github.com/en/actions/learn-github-actions/contexts
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

# https://github.com/xgqfrms/xgqfrms/settings/secrets/actions
# - uses: actions/checkout@v3

# https://docs.github.com/en/actions/learn-github-actions/environment-variables

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # - uses: actions/checkout@v3
      - uses: actions/checkout@v2
      # - uses: yoshi389111/github-profile-3d-contrib@latest
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
      # 执行单行命令 ??? env
      # - name: "Hello env $EMAIL"
      #   run: echo "$EMAIL"
      # - name: "Hello env $FLAG"
      #   if: ${{ env.FLAG == 'true' }}
      #   run: echo "$FLAG"
      # 执行多行命令
      - name: Print env ❓
        run: env | sort
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email xgqfrms@xgqfrms.xyz
          git add -A .
          git commit -m "feat: update GitHub 3D Profile"
          git push
        # run: |
        #   git config user.name ${{ github.repository_owner }}
        #   git config user.email xgqfrms@xgqfrms.xyz  git config user.email ${{ secrets.EMAIL }}
        #   git add -A .
        #   git commit -m "feat: update GitHub 3D Profile"
        #   git push


```
